SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS FILE_LOGGING_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS FILE_LOG_ROTATE_MAX_SIZE_MB INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN IF NOT EXISTS FILE_LOG_ROTATE_INTERVAL TEXT NOT NULL DEFAULT 'daily',
    ADD COLUMN IF NOT EXISTS FILE_LOG_RETENTION_DAYS INTEGER NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS FILE_LOG_MAX_ARCHIVES INTEGER NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS FILE_LOG_COMPRESS BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_FILE_LOG_ROTATE_MAX_SIZE_MB_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_FILE_LOG_ROTATE_MAX_SIZE_MB_CHECK
      CHECK (FILE_LOG_ROTATE_MAX_SIZE_MB BETWEEN 1 AND 10240),
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_FILE_LOG_ROTATE_INTERVAL_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_FILE_LOG_ROTATE_INTERVAL_CHECK
      CHECK (FILE_LOG_ROTATE_INTERVAL IN ('daily', 'weekly')),
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_FILE_LOG_RETENTION_DAYS_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_FILE_LOG_RETENTION_DAYS_CHECK
      CHECK (FILE_LOG_RETENTION_DAYS BETWEEN 1 AND 3650),
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_FILE_LOG_MAX_ARCHIVES_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_FILE_LOG_MAX_ARCHIVES_CHECK
      CHECK (FILE_LOG_MAX_ARCHIVES BETWEEN 1 AND 365);
